sudo: false

language: ruby

cache: bundler

services: mongodb

rvm:
  - 2.3.1

before_install:
  - gem update bundler

before_script:
  - bundle exec danger

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
